continue_outside\.c:3:2: error:.*